# **LSTM/GRU Model**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [41]:
from tensorflow.keras.layers import LSTM,Dropout,Dense,Embedding,GRU

In [30]:
from tensorflow.keras.models import Sequential

# **DATA PREPROCESSING**

In [4]:
df=pd.read_csv("/content/twitter_training.csv (2).zip")

In [13]:
df.columns

Index(['2401', 'Borderlands', 'Positive',
       'im getting on borderlands and i will murder you all ,'],
      dtype='object')

In [14]:
df.describe()

               2401
count  74681.000000
mean    6432.640149
std     3740.423819
min        1.000000
25%     3195.000000
50%     6422.000000
75%     9601.000000
max    13200.000000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74681 entries, 0 to 74680
Data columns (total 4 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   2401                                                   74681 non-null  int64
 1   Borderlands                                            74681 non-null  object
 2   Positive                                               74681 non-null  object
 3   im getting on borderlands and i will murder you all ,  73995 non-null  object
dtypes: int64(1), object(3)
memory usage: 2.3+ MB

In [7]:
df.head(20)

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...
5,2402,Borderlands,Positive,So I spent a few hours making something for fu...
6,2402,Borderlands,Positive,So I spent a couple of hours doing something f...
7,2402,Borderlands,Positive,So I spent a few hours doing something for fun...
8,2402,Borderlands,Positive,So I spent a few hours making something for fu...
9,2402,Borderlands,Positive,2010 So I spent a few hours making something f...
10,2402,Borderlands,Positive,was
11,2403,Borderlands,Neutral,"Rock-Hard La Varlope, RARE & POWERFUL, HANDSOM..."
12,2403,Borderlands,Neutral,"Rock-Hard La Varlope, RARE & POWERFUL, HANDSOM..."
13,2403,Borderlands,Neutral,"Rock-Hard La Varlope, RARE & POWERFUL, HANDSOM..."
14,2403,Borderlands,Neutral,"Rock-Hard La Vita, RARE BUT POWERFUL, HANDSOME..."
15,2403,Borderlands,Neutral,"Live Rock - Hard music La la Varlope, RARE & t..."
16,2403,Borderlands,Neutral,"I-Hard like me, RARE LONDON DE, HANDSOME 2011,..."
17,2404,Borderlands,Positive,that was the first borderlands session in a lo...
18,2404,Borderlands,Positive,this was the first Borderlands session in a lo...
19,2404,Borderlands,Positive,that was the first borderlands session in a lo...

In [8]:
df.tail(20)

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
74661,9197,Nvidia,Neutral,Nvidia therefore doesn ’ t want to give up its...
74662,9197,Nvidia,Neutral,is doesn’t should I give up its password ‘cryp...
74663,9198,Nvidia,Negative,Nvidia really delayed the 3070 2 weeks .
74664,9198,Nvidia,Negative,Nvidia really delayed the 3070 by 2 weeks.
74665,9198,Nvidia,Negative,Nvidia did delay by 3070 2 weeks.
74666,9198,Nvidia,Negative,Nvidia really delayed the 3070 several weeks.
74667,9198,Nvidia,Negative,Nvidia really only delayed the 3070 2 flight w...
74668,9198,Nvidia,Negative,Nvidia really delayed the next 2 weeks.
74669,9199,Nvidia,Positive,Let no elim go unnoticed. . . . NVIDIA Highlig...
74670,9199,Nvidia,Positive,t let Elim go unnoticed.... NVIDIA Highlights ...
74671,9199,Nvidia,Positive,Let no elite go unnoticed... NVIDIA Highlights...
74672,9199,Nvidia,Positive,Let no elim go unnoticed.... NVIDIA Highlights...
74673,9199,Nvidia,Positive,Let a no information elim that go unnoticed......
74674,9199,Nvidia,Positive,<unk> my elim be no.... NVIDIA Highlights Pict...
74675,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74676,9200,Nvidia,Positive,Just realized that the Windows partition of my...
74677,9200,Nvidia,Positive,Just realized that my Mac window partition is ...
74678,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74679,9200,Nvidia,Positive,Just realized between the windows partition of...
74680,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...

In [9]:
df.isnull().sum()

2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    686
dtype: int64

In [11]:
df.isna().sum()

2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    686
dtype: int64

In [16]:
column_to_fill = 'im getting on borderlands and i will murder you all ,'
mode_value = df[column_to_fill].mode()[0]
df[column_to_fill] = df[column_to_fill].fillna(mode_value)

In [18]:
df.isnull().sum()

2401                                                     0
Borderlands                                              0
Positive                                                 0
im getting on borderlands and i will murder you all ,    0
dtype: int64

# **Data Split**

In [20]:
x=df['im getting on borderlands and i will murder you all ,']
y=df['Positive']

In [21]:
print(y.head())

0    Positive
1    Positive
2    Positive
3    Positive
4    Positive
Name: Positive, dtype: object

In [22]:
print(x.head())

0    I am coming to the borders and I will kill you...
1    im getting on borderlands and i will kill you ...
2    im coming on borderlands and i will murder you...
3    im getting on borderlands 2 and i will murder ...
4    im getting into borderlands and i can murder y...
Name: im getting on borderlands and i will murder you all ,, dtype: object

# **Label Encoding**

In [24]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [26]:
print(y)

[3 3 3 ... 3 3 3]

# **Tokenization**

In [27]:
from tensorflow.keras.preprocessing.text import Tokenizer
token=Tokenizer(num_words=5000)
token.fit_on_texts(x)
sq = token.texts_to_sequences(x)

# **Padding**

In [28]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
x_pad=pad_sequences(sq,maxlen=20)

In [32]:
model = Sequential([

    Embedding(input_dim=5000, output_dim=64),

    LSTM(64),
    Dropout(0.5),

    Dense(4, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [33]:
model.build(input_shape=(None,20))

In [34]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 20, 64)         │       320,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 64)             │        33,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 4)              │           260 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 353,284 (1.35 MB)

 Trainable params: 353,284 (1.35 MB)

 Non-trainable params: 0 (0.00 B)

In [35]:
print(x_pad.dtype)
print(y.dtype)

int32
int64

In [36]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x_pad,
    y,
    test_size=0.2,
    random_state=42
)

In [37]:
model.fit(X_train,y_train,epochs=10,validation_data=(X_test,y_test) )

Epoch 1/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 39s 20ms/step - accuracy: 0.5864 - loss: 1.0012 - val_accuracy: 0.6713 - val_loss: 0.8267
Epoch 2/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 39s 18ms/step - accuracy: 0.7190 - loss: 0.7248 - val_accuracy: 0.7165 - val_loss: 0.7233
Epoch 3/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 34s 18ms/step - accuracy: 0.7776 - loss: 0.5852 - val_accuracy: 0.7466 - val_loss: 0.6700
Epoch 4/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 33s 18ms/step - accuracy: 0.8113 - loss: 0.4983 - val_accuracy: 0.7581 - val_loss: 0.6582
Epoch 5/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 35s 18ms/step - accuracy: 0.8367 - loss: 0.4315 - val_accuracy: 0.7722 - val_loss: 0.6545
Epoch 6/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 33s 18ms/step - accuracy: 0.8577 - loss: 0.3790 - val_accuracy: 0.7792 - val_loss: 0.6451
Epoch 7/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 35s 19ms/step - accuracy: 0.8743 - loss: 0.3348 - val_accuracy: 0.7921 - val_loss: 0.6476
Epoch 8/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 33s 18ms/step - accuracy: 0.8873 - loss: 0.2963 - val_accuracy: 0.7944 - val_loss: 0.6539
Epoch 9/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 34s 18ms/step - accuracy: 0.8982 - loss: 0.2677 - val_accuracy: 0.7977 - val_loss: 0.6737
Epoch 10/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 34s 18ms/step - accuracy: 0.9071 - loss: 0.2417 - val_accuracy: 0.8016 - val_loss: 0.7004

In [38]:
loss, accuracy = model.evaluate(X_test, y_test)
print( "Loss :",loss)

print("Accuracy:", accuracy)

467/467 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8016 - loss: 0.7004
Loss : 0.7003888487815857
Accuracy: 0.8016335368156433

In [39]:
labels = {
    0: "Irrelevant",
    1: "Negative",
    2: "Neutral",
    3: "Positive"
}

In [40]:
text = ["I am  ok"]

seq = token.texts_to_sequences(text)

pad = pad_sequences(seq, maxlen=20)

pred = model.predict(pad)

predicted_class = np.argmax(pred)

print("Predicted Sentiment:",
      labels[predicted_class])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step
Predicted Sentiment: Neutral

In [42]:
model = Sequential([

    Embedding(input_dim=5000, output_dim=64),

    GRU(64),
    Dropout(0.5),

    Dense(4, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [43]:
model.build(input_shape=(None,20))

In [44]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 20, 64)         │       320,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ (None, 64)             │        24,960 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │           260 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 345,220 (1.32 MB)

 Trainable params: 345,220 (1.32 MB)

 Non-trainable params: 0 (0.00 B)

In [45]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x_pad,
    y,
    test_size=0.2,
    random_state=42
)

In [46]:
model.fit(X_train,y_train,epochs=10,validation_data=(X_test,y_test) )

Epoch 1/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 42s 22ms/step - accuracy: 0.5871 - loss: 1.0019 - val_accuracy: 0.6653 - val_loss: 0.8351
Epoch 2/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 37s 20ms/step - accuracy: 0.7234 - loss: 0.7207 - val_accuracy: 0.7195 - val_loss: 0.7199
Epoch 3/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 34s 18ms/step - accuracy: 0.7796 - loss: 0.5845 - val_accuracy: 0.7439 - val_loss: 0.6748
Epoch 4/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 41s 18ms/step - accuracy: 0.8150 - loss: 0.4956 - val_accuracy: 0.7558 - val_loss: 0.6611
Epoch 5/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 42s 19ms/step - accuracy: 0.8408 - loss: 0.4295 - val_accuracy: 0.7741 - val_loss: 0.6361
Epoch 6/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 34s 18ms/step - accuracy: 0.8573 - loss: 0.3797 - val_accuracy: 0.7840 - val_loss: 0.6358
Epoch 7/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 35s 19ms/step - accuracy: 0.8750 - loss: 0.3374 - val_accuracy: 0.7909 - val_loss: 0.6440
Epoch 8/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 34s 18ms/step - accuracy: 0.8873 - loss: 0.3027 - val_accuracy: 0.7959 - val_loss: 0.6514
Epoch 9/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 35s 19ms/step - accuracy: 0.8981 - loss: 0.2713 - val_accuracy: 0.7985 - val_loss: 0.7040
Epoch 10/10
1867/1867 ━━━━━━━━━━━━━━━━━━━━ 41s 19ms/step - accuracy: 0.9069 - loss: 0.2478 - val_accuracy: 0.7996 - val_loss: 0.7230

In [47]:
loss, accuracy = model.evaluate(X_test, y_test)
print( "Loss :",loss)

print("Accuracy:", accuracy)

467/467 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7996 - loss: 0.7230
Loss : 0.722999095916748
Accuracy: 0.799558162689209